
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-serviceaccount
  namespace: jerney
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/team-a

---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: jerney
spec:
  refreshInterval: 10s
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-serviceaccount
            namespace: jerney


---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: jerney
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: db-secret
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: POSTGRES_PASSWORD
  - secretKey: POSTGRES_DB
    remoteRef:
      key: POSTGRES_DB

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3
  encrypted: "true"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jerney-db-pvc
  namespace: jerney
  labels:
    app.kubernetes.io/name: jerney-db
    app.kubernetes.io/part-of: jerney
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-sc


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: jerney
  labels:
    app.kubernetes.io/name: jerney-db
    app.kubernetes.io/part-of: jerney
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jerney-db
      app.kubernetes.io/part-of: jerney
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jerney-db
        app.kubernetes.io/part-of: jerney
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          protocol: TCP
        envFrom:
        - secretRef:
            name: db-secret
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "jerney_user", "-d", "jerney_db"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "jerney_user", "-d", "jerney_db"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      restartPolicy: Always
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: jerney-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: jerney-db-svc
  namespace: jerney
spec:
  selector:
    app.kubernetes.io/name: jerney-db
    app.kubernetes.io/part-of: jerney
    app.kubernetes.io/component: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
