name: IAC DevSecOps Pipeline
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
        paths:
            - 'deploy/iac/**'
            - '.github/workflows/iac-devsecops-pipeline.yaml'
permissions:
    contents: read
    id-token: write
jobs:
    setup-environment:
        runs-on: ubuntu-latest
        outputs:
            target-env: ${{ steps.setting-environment.outputs.TARGET_ENV }}
        defaults:
            run:
                working-directory: ./deploy/iac
        steps:
            - name: Setting up environment
              id: setting-environment
              run: |
                if [[ ${{ github.event_name }} == 'pull_request' ]]; then
                    echo "TARGET_ENV=iac-dev" >> $GITHUB_OUTPUT
                else
                    echo "TARGET_ENV=iac-prod" >> $GITHUB_OUTPUT
                fi
    iac-scan:
        runs-on: ubuntu-latest
        needs:
            - setup-environment
        outputs:
            target-env: ${{ needs.setup-environment.outputs.target-env }}
        defaults:
            run:
                working-directory: ./deploy/iac
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run Checkov on Terraform
              uses: bridgecrewio/checkov-action@v12
              continue-on-error: true
              with:
                directory: ./deploy/iac
                framework: terraform
                soft_fail: false
                skip_check: CKV_AWS_39,CKV_AWS_40,CKV_AWS_58
                output_format: cli
    iac-plan:
        runs-on: ubuntu-latest
        needs:
            - setup-environment
        defaults:
            run:
                working-directory: ./deploy/iac
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: "arn:aws:iam::829007908826:role/gha-syedsulaimana-org-pipeline-role"
                role-session-name: github-actions-session
                aws-region: ap-south-1
            - name: Run Terraform plan
              run: |
                terraform plan
    iac-apply:
        runs-on: ubuntu-latest
        needs:
            - setup-environment
            - iac-scan
            - iac-plan
        defaults:
            run:
                working-directory: ./deploy/iac
        environment: ${{ needs.setup-environment.outputs.target-env }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: "arn:aws:iam::829007908826:role/gha-syedsulaimana-org-pipeline-role"
                role-session-name: github-actions-session
                aws-region: ${{ vars.AWS_REGION }}
            - name: Run Terraform apply
              run: |
                terraform apply --auto-approve
